// ═══════════════════════════════════════════════════════════
// BROTHERHOOD CONNECT — Research Content
// 33 peer-reviewed sources | Decades of longitudinal research
// ═══════════════════════════════════════════════════════════

export const PILLARS = [
  {
    id: "physical",
    icon: "💪",
    title: "Physical Health & Longevity",
    color: "#2D6A4F",
    gradient: "linear-gradient(135deg, #2D6A4F 0%, #40916C 100%)",
    tagline: "Your body thrives when connected",
    stat: "15–26%",
    statLabel: "reduced mortality risk through social connection",
    overview: "Social isolation increases premature mortality by approximately 26%, comparable to smoking 15 cigarettes daily. For men, the absence of a partner and limited family contact drives a 15% increase in 20-year mortality risk. Social connection reduces cortisol, lowers inflammation markers (CRP, IL-6), and strengthens immune function.",
    research: [
      { finding: "Social isolation increased 20-year mortality risk by 15% for men (HR = 1.15, 95% CI 1.09–1.21).", source: "Aartsen et al. (2024), Frontiers in Public Health" },
      { finding: "Living alone was associated with flattened diurnal cortisol and higher C-reactive protein levels.", source: "Zilioli & Jiang (2021), Psychoneuroendocrinology" },
      { finding: "Loneliness predicted all-cause, cancer, and cardiovascular disease mortality in a 23-year follow-up of 2,588 men.", source: "Kraav et al. (2020), Aging & Mental Health" },
    ],
    practices: [
      "Schedule a weekly walk, run, or workout with a friend or group",
      "Join a community sports league — cricket, football, basketball, or dominoes",
      "Share a meal with brothers at least once a week",
      "Find an accountability partner for health goals",
      "Get regular health screenings — bring a friend for support",
    ],
    reflection: "When was the last time you worked out with a group or a friend? How did the energy compare to training solo?",
  },
  {
    id: "mental",
    icon: "🧠",
    title: "Mental Health & Resilience",
    color: "#7B2D8E",
    gradient: "linear-gradient(135deg, #7B2D8E 0%, #A855F7 100%)",
    tagline: "Strength is knowing when to lean on others",
    stat: "58%",
    statLabel: "reduction in suicidal ideation with strong social support",
    overview: "Men account for ~75% of all suicide deaths in Western nations. Yet social support from friends is protective against both suicidal ideation and planning. Loneliness has medium-to-large effects on depression, anxiety, and overall wellbeing. Support groups providing safe space for discussion are among the most effective interventions for men.",
    research: [
      { finding: "Middle/high social support reduced suicidal ideation probability by 58% over five years (OR = 0.42).", source: "Otten et al. (2022), Journal of Affective Disorders" },
      { finding: "Greater perceived social support from friends was protective against suicidal ideation and planning during COVID-19.", source: "Seidler et al. (2023), BMC Psychiatry" },
      { finding: "Black male college students with better mental health knowledge sought help more often; help-seeking reduced stigma.", source: "Gere & Salimi (2025), American Journal of Men's Health" },
    ],
    practices: [
      "Name one emotion you felt today — share it with someone you trust",
      "Check in on a brother you haven't heard from in a while",
      "Learn to say 'I'm not okay' without shame",
      "Explore a men's circle, therapy group, or guided discussion",
      "Practice active listening — hold space without fixing",
    ],
    reflection: "What was the last difficult emotion you shared with another man? What held you back, or what made it possible?",
  },
  {
    id: "cognitive",
    icon: "🔮",
    title: "Cognitive Function & Brain Health",
    color: "#1565C0",
    gradient: "linear-gradient(135deg, #1565C0 0%, #42A5F5 100%)",
    tagline: "Conversation sharpens the mind",
    stat: "80+",
    statLabel: "years of longitudinal data linking social ties to cognitive sharpness",
    overview: "Decades of longitudinal research show that socially connected men at 50 maintained sharp cognitive function at 80. Social interaction exercises neural networks for language, emotion, memory, and executive function. Deeper conversations boost social connectedness more than surface-level exchanges.",
    research: [
      { finding: "Both quantity and quality of social interactions were robustly associated with greater wellbeing (N = 256, 3,206 observations).", source: "Sun, Harris, & Vazire (2019), Journal of Personality and Social Psychology" },
      { finding: "Social affiliation-seeking linked to activity in brain reward circuits (dorsal raphe, substantia nigra, anterior insula).", source: "Garud et al. (2025), PNAS" },
      { finding: "Chronic stress + social isolation reduced hippocampal neurogenesis and promoted depressive-like behaviour.", source: "De Preez et al. (2020), Brain, Behavior, and Immunity" },
    ],
    practices: [
      "Engage in deep conversation — move beyond 'what's up' to 'what's real'",
      "Join a book club, reasoning circle, or debate group",
      "Play strategy games together — chess, dominoes, cards",
      "Learn something new with a partner — language, skill, instrument",
      "Share stories from your life — storytelling builds neural pathways",
    ],
    reflection: "Think of a conversation that changed how you see the world. What made it so powerful?",
  },
  {
    id: "economic",
    icon: "📈",
    title: "Economic & Professional Growth",
    color: "#B8860B",
    gradient: "linear-gradient(135deg, #B8860B 0%, #DAA520 100%)",
    tagline: "We rise together",
    stat: "∞",
    statLabel: "potential of collective economic power",
    overview: "Social capital — the resources available through social networks — plays a decisive role in economic mobility. For Black and brown men facing structural barriers, peer groups serve as conduits for employment, mentorship, and entrepreneurship. The Caribbean susu (community savings) system demonstrates how social groups can function as parallel financial institutions.",
    research: [
      { finding: "Structural racism in housing, education, income, and employment created compounding stressors for Black men, reducing optimism.", source: "Willie et al. (2025), Injury Epidemiology" },
      { finding: "High contextual stress during the transition to fatherhood was associated with increased substance misuse among 476 Black American men.", source: "Curtis et al. (2022), Substance Use & Misuse" },
    ],
    practices: [
      "Start or join a savings circle (susu/partner/lending group)",
      "Create a professional networking group with 5–10 brothers",
      "Mentor a younger man in your field — and find a mentor for yourself",
      "Share job opportunities, business contacts, and resources openly",
      "Build a skill-share collective — everyone teaches, everyone learns",
    ],
    reflection: "Who opened a door for you professionally? How can you open that door for someone else?",
  },
  {
    id: "family",
    icon: "🏠",
    title: "Family & Relational Wellbeing",
    color: "#C0392B",
    gradient: "linear-gradient(135deg, #C0392B 0%, #E74C3C 100%)",
    tagline: "Strong bonds strengthen every relationship",
    stat: "6",
    statLabel: "key strategies for wellbeing strengthened by community support",
    overview: "Men with strong friendships maintain more satisfying relationships across all areas of life. Whether you are a father, uncle, brother, son, or mentor, social support networks help you show up better for those who depend on you. African American men embedded in supportive networks develop positive identity formation and adaptive coping strategies.",
    research: [
      { finding: "African American fathers drew on community support to develop 6 key parenting strategies including cultural identity cultivation.", source: "Cooper et al. (2020), Journal of Adolescence" },
      { finding: "Friendship quality was positively associated with life satisfaction (7/7 studies), happiness (5/5), and self-esteem (5/6).", source: "Alsarrani et al. (2022), BMC Public Health" },
    ],
    practices: [
      "Create a circle of men who share wins and struggles openly",
      "Model emotional openness for the young people in your life",
      "Build relationships with other men in your community",
      "Invest in your own social health so you can be there for others",
      "Connect elders in your family with younger members intentionally",
    ],
    reflection: "How has a friendship made you better at showing up for the people in your life? What lesson from a brother changed how you carry yourself?",
  },
  {
    id: "identity",
    icon: "🌍",
    title: "Identity & Cultural Belonging",
    color: "#E65100",
    gradient: "linear-gradient(135deg, #E65100 0%, #FF8F00 100%)",
    tagline: "Know where you come from to know where you're going",
    stat: "7",
    statLabel: "recovery themes identified for African & Caribbean men",
    overview: "Social groups serve as primary sites of identity construction. For African and Caribbean men, recovery from mental distress is a journey addressing 'social suffering' at the intersections of masculinity, race, and mental health. Caribbean traditions — yard culture, liming, reasoning — represent sophisticated models of male social connection.",
    research: [
      { finding: "Recovery for African/Caribbean men involved 7 themes: recovering from social suffering, leading a normal life, regaining control, hope, identity, reduced medical involvement, and healing.", source: "Southby, Keating, & Joseph (2021), IJMSCH" },
      { finding: "Black male adolescents understood mental health through masculinity — being 'in control and strong' — creating barriers to seeking help.", source: "Meechan, John, & Hanna (2021), Children and Youth Services Review" },
      { finding: "Men's patterns of social connectedness are diverse, challenging narratives that frame male relationships as purely instrumental.", source: "McKenzie et al. (2018), American Journal of Men's Health" },
    ],
    practices: [
      "Learn and share the history of your community, people, and ancestors",
      "Attend cultural events that celebrate your heritage",
      "Create spaces for 'reasoning' — deep, open-ended collective dialogue",
      "Document family stories and oral traditions before they're lost",
      "Connect with diaspora communities to bridge distance and culture",
    ],
    reflection: "What cultural tradition from your heritage makes you feel most connected? How can you pass it on?",
  },
  {
    id: "community",
    icon: "🤝",
    title: "Community Safety & Civic Life",
    color: "#37474F",
    gradient: "linear-gradient(135deg, #37474F 0%, #607D8B 100%)",
    tagline: "Connected men build safer communities",
    stat: "5",
    statLabel: "themes shaping formerly incarcerated Black men's mental health-seeking",
    overview: "Communities with stronger social cohesion experience lower rates of violence. Men's social groups build collective efficacy — the willingness to intervene for the common good. For formerly incarcerated Black men, rebuilding social networks is critical for successful reintegration.",
    research: [
      { finding: "Formerly incarcerated Black men identified 5 themes: self-assessment, self-reliance, expressing needs, mistrust of services, and navigating stigma.", source: "Addison et al. (2025), Journal of Racial and Ethnic Health Disparities" },
      { finding: "Men emphasised receiving support from trusted individuals in informal settings; connecting with others interrupted the suicidal process.", source: "Struszczyk, Galdas, & Tiffin (2019), Journal of Mental Health" },
    ],
    practices: [
      "Volunteer together — service builds bonds and purpose",
      "Become a mentor or 'big brother' in your community",
      "Support re-entry programmes for returning citizens",
      "Organise neighbourhood gatherings — cookouts, clean-ups, game nights",
      "Advocate for community spaces — parks, centres, cultural venues",
    ],
    reflection: "What would your community look like if every man in it had five brothers he could count on?",
  },
];

export const CONNECT_FRAMEWORK = [
  { letter: "C", title: "Culturally Grounded Design", desc: "Programmes must be designed from within the cultural context of the men they serve." },
  { letter: "O", title: "Organic Entry Points", desc: "Meet men where they already are — barbershops, sports fields, churches, workplaces." },
  { letter: "N", title: "Non-Prescriptive Structure", desc: "Participant-driven, not expert-led. Men set the agenda." },
  { letter: "N", title: "Normalise Vulnerability", desc: "Reframe vulnerability as strength. Model emotional openness." },
  { letter: "E", title: "Embed Activity", desc: "Activity-based programmes engage men more effectively than talk-only formats." },
  { letter: "C", title: "Create Continuity", desc: "No quick fixes. Build practices into lifestyle through regular gathering." },
  { letter: "T", title: "Track and Adapt", desc: "Assess wellbeing continuously. Adapt programmes to evolving needs." },
];

